---
- name: Provision app servers
  hosts: app_servers
  become: true
  roles:
    - role: env_sync
      vars:
        sync_public_env: true
        sync_private_env: true
    - docker

- name: Provision MySQL servers
  hosts: mysql_servers
  become: true
  roles:
    - role: env_sync
      vars:
        sync_public_env: false
        sync_private_env: true
    - mysql

- name: Provision Redis servers
  hosts: redis_servers
  become: true
  roles:
    - redis

- name: Provision load balancers
  hosts: lb_servers
  become: true
  roles:
    - role: env_sync
      vars:
        sync_public_env: true
        sync_private_env: true
    - nginx
