---
nginx_domain: example.com
public_env_file: "/var/www/html/edugarden/.env"
private_env_file: "{{ secret_env_file | default('/opt/edugarden/secret.env.production') }}"
nginx_client_max_body_size: 64m
nginx_proxy_read_timeout: 300s
nginx_proxy_connect_timeout: 60s
nginx_proxy_send_timeout: 300s
nginx_ssl_certificate: /etc/letsencrypt/live/{{ nginx_domain }}/fullchain.pem
nginx_ssl_certificate_key: /etc/letsencrypt/live/{{ nginx_domain }}/privkey.pem
nginx_upstream_servers: >-
  {{
    groups['app_servers']
    | list
  }}
